import { Brain, Moon, Activity, Users, ShieldCheck } from 'lucide-react';
import React from 'react';

export const ESTUDOS = [
  {
    slug: 'epilepsia-dravet-cannabidiol',
    categoria: 'Epilepsia',
    condicao: 'Epilepsia e Condições Neurológicas',
    titulo: 'CBD e epilepsia: o que este estudo mostrou',
    subtitulo: 'Ensaio clínico randomizado avaliou o canabidiol em crianças e jovens com Síndrome de Dravet — uma forma grave e resistente de epilepsia.',
    resumoCurto: 'Estudo publicado no New England Journal of Medicine mostrou redução significativa na frequência de crises convulsivas com o uso de canabidiol em pacientes com Síndrome de Dravet.',
    destaque: 'Redução de 39% na frequência de crises convulsivas',
    icon: (props) => <Brain {...props} />,
    pmid: '28538134',
    doi: '10.1056/NEJMoa1611618',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28538134/',
    referencia: 'Devinsky O, Cross JH, Laux L, et al. Trial of Cannabidiol for Drug-Resistant Seizures in the Dravet Syndrome. N Engl J Med. 2017;376(21):2011-2020.',
    journal: 'New England Journal of Medicine',
    ano: 2017,
    design: 'Ensaio clínico randomizado, duplo-cego, controlado por placebo',
    populacao: '120 crianças e jovens adultos com Síndrome de Dravet e crises resistentes a medicamentos',
    duracao: '14 semanas de tratamento, com 4 semanas de período basal',
    oQueAvaliou: 'Este estudo avaliou a eficácia e segurança do canabidiol (CBD) oral, na dose de 20 mg/kg/dia, em crianças e jovens com Síndrome de Dravet — uma forma grave de epilepsia infantil associada a crises convulsivas frequentes e resistentes aos tratamentos convencionais. Todos os participantes mantiveram seus medicamentos antiepilépticos habituais durante o estudo.',
    achados: [
      { texto: 'A frequência mediana de crises convulsivas mensais caiu de 12,4 para 5,9 no grupo que recebeu canabidiol — no grupo placebo, a redução foi de 14,9 para 14,1.' },
      { texto: '43% dos pacientes com CBD tiveram redução de pelo menos 50% nas crises convulsivas, comparado a 27% no grupo placebo.' },
      { texto: '62% dos cuidadores relataram melhora na condição geral dos pacientes tratados com canabidiol, contra 34% no grupo placebo.' },
      { texto: 'A frequência total de crises (todos os tipos) também foi significativamente reduzida no grupo tratado com CBD.' },
      { texto: '5% dos pacientes com canabidiol ficaram livres de crises durante o estudo, contra 0% no grupo placebo.' },
    ],
    significado: 'Este estudo, publicado em um dos periódicos médicos de maior prestígio no mundo, forneceu evidência robusta de que o canabidiol pode ser eficaz na redução de crises convulsivas em uma das formas mais graves de epilepsia infantil. Os resultados contribuíram para a aprovação do Epidiolex (canabidiol farmacêutico) pelo FDA como tratamento para a Síndrome de Dravet.',
    limites: [
      'Os eventos adversos foram mais frequentes no grupo CBD: diarreia, vômitos, fadiga, febre, sonolência e alterações em exames hepáticos.',
      'Houve mais desistências no grupo que recebeu canabidiol do que no grupo placebo.',
      'Não houve redução significativa nas crises não convulsivas.',
      'O estudo durou 14 semanas — dados de longo prazo são necessários.',
      'A pesquisa foi financiada pela GW Pharmaceuticals, fabricante do produto testado.',
    ],
  },
  {
    slug: 'insonia-cannabis-medicinal',
    categoria: 'Distúrbios do Sono',
    condicao: 'Ansiedade e Distúrbios do Sono',
    titulo: 'Cannabis medicinal e insônia: o que a pesquisa observou',
    subtitulo: 'Ensaio clínico cruzado avaliou a eficácia de um extrato canabinoide sublingual em adultos com insônia crônica.',
    resumoCurto: 'Estudo publicado na revista Sleep mostrou que 2 semanas de uso de extrato canabinoide sublingual melhoraram significativamente a qualidade do sono e o tempo total de sono.',
    destaque: 'Aumento de 64,6 minutos no tempo total de sono',
    icon: (props) => <Moon {...props} />,
    pmid: '34115851',
    doi: '10.1093/sleep/zsab149',
    url: 'https://pubmed.ncbi.nlm.nih.gov/34115851/',
    referencia: 'Walsh JH, Maddison KJ, Rankin T, et al. Treating insomnia symptoms with medicinal cannabis: a randomized, crossover trial of the efficacy of a cannabinoid medicine compared with placebo. Sleep. 2021;44(11):zsab149.',
    journal: 'Sleep',
    ano: 2021,
    design: 'Ensaio clínico randomizado, duplo-cego, controlado por placebo, com desenho cruzado (crossover)',
    populacao: '24 adultos com insônia crônica (sintomas há 3 meses ou mais); 23 completaram o protocolo. Média de idade: 53 anos; 87% mulheres.',
    duracao: '2 semanas de tratamento com cada substância (extrato ou placebo), com período de washout entre as fases',
    oQueAvaliou: 'O estudo avaliou a segurança e eficácia de um extrato canabinoide sublingual (ZTL-101) administrado durante 2 semanas em adultos com insônia crônica. A severidade da insônia foi medida pelo Insomnia Severity Index (ISI), e o sono foi avaliado por diário, actigrafia e polissonografia.',
    achados: [
      { texto: 'O índice de severidade da insônia (ISI) diminuiu 5,07 pontos com o tratamento — uma diferença estatisticamente significativa.' },
      { texto: 'O tempo total de sono aumentou em média 64,6 minutos por noite.' },
      { texto: 'A latência do sono (tempo para adormecer) diminuiu 8,45 minutos.' },
      { texto: 'A qualidade subjetiva do sono melhorou significativamente, assim como a sensação de descanso ao acordar.' },
      { texto: 'Dados de actigrafia confirmaram melhora na eficiência do sono (+2,9%) e redução do tempo acordado após início do sono.' },
    ],
    significado: 'Este é um dos poucos ensaios clínicos randomizados e controlados sobre cannabis medicinal e insônia. Os resultados sugerem que o extrato canabinoide testado pode melhorar a qualidade e a duração do sono em adultos com insônia crônica, com boa tolerabilidade. Entretanto, por se tratar de um estudo pequeno e de curta duração, os achados são promissores, mas não definitivos.',
    limites: [
      'A amostra foi pequena: apenas 24 participantes randomizados.',
      'A duração do tratamento foi curta (2 semanas) — efeitos de longo prazo não foram avaliados.',
      'A população foi predominantemente feminina (87%), limitando a generalização dos resultados.',
      'Ocorreram 40 eventos adversos leves durante o tratamento, embora todos tenham sido resolvidos rapidamente.',
      'Estudos maiores e mais longos são necessários para confirmar os achados.',
    ],
  },
  {
    slug: 'dor-cronica-cannabis',
    categoria: 'Dor Crônica',
    condicao: 'Dores Crônicas e Inflamações Severas',
    titulo: 'Cannabis e dor crônica: principais achados do estudo',
    subtitulo: 'Ensaio clínico randomizado testou um inalador de cannabis com doses precisas de THC em pacientes com dor crônica neuropática.',
    resumoCurto: 'Estudo publicado no European Journal of Pain demonstrou que doses baixas e precisas de THC inalado reduziram significativamente a dor crônica sem comprometer a função cognitiva.',
    destaque: 'Redução significativa da dor com início rápido (menos de 5 minutos)',
    icon: (props) => <Activity {...props} />,
    pmid: '32445190',
    doi: '10.1002/ejp.1605',
    url: 'https://pubmed.ncbi.nlm.nih.gov/32445190/',
    referencia: 'Almog S, Aharon-Peretz J, Vulfsons S, et al. The pharmacokinetics, efficacy, and safety of a novel selective-dose cannabis inhaler in patients with chronic pain: A randomized, double-blinded, placebo-controlled trial. Eur J Pain. 2020;24(8):1505-1516.',
    journal: 'European Journal of Pain',
    ano: 2020,
    design: 'Ensaio clínico randomizado, duplo-cego, controlado por placebo, com desenho cruzado de 3 braços',
    populacao: '27 pacientes adultos com dor crônica neuropática e síndrome de dor regional complexa (CRPS)',
    duracao: 'Sessões únicas de inalação com período de avaliação de 150 minutos por sessão',
    oQueAvaliou: 'O estudo avaliou a farmacocinética, o efeito analgésico, o desempenho cognitivo e a segurança de um inalador de cannabis de dose seletiva. Os pacientes receberam doses únicas de 0,5 mg de THC, 1 mg de THC ou placebo, em sessões separadas, de forma cruzada.',
    achados: [
      { texto: 'Ambas as doses (0,5 mg e 1 mg de THC) produziram redução significativa da dor em comparação com a linha de base.' },
      { texto: 'A dose de 1 mg de THC foi significativamente superior ao placebo na redução da dor.' },
      { texto: 'O início do efeito analgésico foi rápido: o pico de concentração plasmática ocorreu em 3,7 a 4,4 minutos.' },
      { texto: 'A redução da dor foi sustentada por até 150 minutos após a inalação.' },
      { texto: 'Não foram observados comprometimentos cognitivos nas doses testadas.' },
      { texto: 'Os eventos adversos foram predominantemente leves e se resolveram espontaneamente.' },
    ],
    significado: 'Este estudo demonstrou que doses muito baixas e precisas de THC inalado podem reduzir a dor crônica de forma rápida e com boa tolerabilidade. A ausência de impacto cognitivo nas doses testadas é um achado relevante, pois sugere que, com dosagem adequada, é possível obter alívio da dor sem os efeitos psicoativos tipicamente associados ao THC.',
    limites: [
      'A amostra foi pequena: 27 pacientes.',
      'O estudo avaliou sessões únicas de inalação — não o uso prolongado.',
      'Os resultados podem não ser generalizáveis para outros tipos de dor crônica.',
      'A dose de 0,5 mg não atingiu diferença estatística em relação ao placebo, embora tenha diferido da linha de base.',
      'Estudos de longo prazo são necessários para avaliar eficácia e segurança com uso continuado.',
    ],
  },
  {
    slug: 'autismo-cbd',
    categoria: 'Espectro Autista',
    condicao: 'Espectro Autista (TEA)',
    titulo: 'CBD no autismo: resultados observados em crianças',
    subtitulo: 'Ensaio clínico randomizado avaliou a eficácia e segurança de extrato de cannabis rico em CBD em crianças com Transtorno do Espectro Autista.',
    resumoCurto: 'Estudo brasileiro publicado no Trends in Psychiatry and Psychotherapy mostrou melhoras significativas em interação social, ansiedade e agitação psicomotora em crianças com TEA tratadas com extrato rico em CBD.',
    destaque: 'Melhora significativa na interação social e na ansiedade',
    icon: (props) => <Users {...props} />,
    pmid: '35617670',
    doi: '10.47626/2237-6089-2021-0396',
    url: 'https://pubmed.ncbi.nlm.nih.gov/35617670/',
    referencia: 'Silva Junior EA, Medeiros WMB, Santos JPM, et al. Evaluation of the efficacy and safety of cannabidiol-rich cannabis extract in children with autism spectrum disorder: randomized, double-blind, and placebo-controlled clinical trial. Trends Psychiatry Psychother. 2024;46:e20210396.',
    journal: 'Trends in Psychiatry and Psychotherapy',
    ano: 2024,
    design: 'Ensaio clínico randomizado, duplo-cego, controlado por placebo',
    populacao: '60 crianças entre 5 e 11 anos de idade com diagnóstico de Transtorno do Espectro Autista (TEA)',
    duracao: '12 semanas de tratamento',
    oQueAvaliou: 'O estudo avaliou a eficácia e segurança de um extrato de cannabis rico em canabidiol (CBD) em crianças com TEA. As crianças foram divididas em dois grupos: tratamento com o extrato e controle com placebo. Foram medidos parâmetros como interação social, ansiedade, agitação psicomotora, alimentação e concentração.',
    achados: [
      { texto: 'Melhora estatisticamente significativa na interação social — um dos critérios diagnósticos centrais do TEA.' },
      { texto: 'Redução significativa nos níveis de ansiedade dos participantes tratados.' },
      { texto: 'Redução significativa da agitação psicomotora.' },
      { texto: 'Melhora no padrão alimentar (número de refeições por dia).' },
      { texto: 'Melhora na concentração em casos de TEA leve.' },
      { texto: 'Apenas 9,7% das crianças tratadas apresentaram efeitos adversos — todos leves (tontura, insônia, cólica e ganho de peso).' },
    ],
    significado: 'Este é um dos primeiros ensaios clínicos randomizados e controlados a avaliar o uso de extrato de cannabis rico em CBD especificamente em crianças com autismo. Os resultados são promissores por mostrarem melhora em aspectos centrais do TEA, como a interação social, com um perfil de segurança favorável. Por se tratar de um estudo brasileiro, os achados são especialmente relevantes para o contexto da CEBEDÊ.',
    limites: [
      'A amostra, embora maior que muitos estudos similares, ainda é relativamente pequena (60 crianças).',
      'O tratamento durou 12 semanas — efeitos de longo prazo não foram avaliados.',
      'A melhora na concentração foi significativa apenas nos casos de TEA leve.',
      'O estudo não incluiu biomarcadores objetivos (como exames de imagem ou testes laboratoriais).',
      'Mais estudos multicêntricos e com amostras maiores são necessários para confirmar os achados.',
    ],
  },
  {
    slug: 'ansiedade-social-cbd',
    categoria: 'Ansiedade',
    condicao: 'Ansiedade e Distúrbios do Sono',
    titulo: 'CBD e ansiedade social: resumo simplificado do estudo',
    subtitulo: 'Ensaio clínico duplo-cego avaliou o efeito ansiolítico do canabidiol em adolescentes japoneses com transtorno de ansiedade social.',
    resumoCurto: 'Estudo publicado na Frontiers in Psychology mostrou que o tratamento repetido com CBD reduziu significativamente a ansiedade em adolescentes com transtorno de ansiedade social.',
    destaque: 'Redução significativa da ansiedade medida por duas escalas diferentes',
    icon: (props) => <ShieldCheck {...props} />,
    pmid: '31787910',
    doi: '10.3389/fpsyg.2019.02466',
    url: 'https://pubmed.ncbi.nlm.nih.gov/31787910/',
    referencia: 'Masataka N. Anxiolytic Effects of Repeated Cannabidiol Treatment in Teenagers With Social Anxiety Disorders. Front Psychol. 2019;10:2466.',
    journal: 'Frontiers in Psychology',
    ano: 2019,
    design: 'Ensaio clínico randomizado, duplo-cego, controlado por placebo',
    populacao: '37 adolescentes japoneses (18-19 anos) com diagnóstico de transtorno de ansiedade social (TAS) e transtorno de personalidade evitativa',
    duracao: '4 semanas de tratamento com CBD (300 mg/dia)',
    oQueAvaliou: 'O estudo avaliou se o tratamento repetido com canabidiol (CBD) poderia reduzir a ansiedade em adolescentes com transtorno de ansiedade social. Os participantes foram divididos em grupo CBD (17 participantes, 300 mg/dia) e grupo placebo (20 participantes), com avaliação da ansiedade por duas escalas validadas.',
    achados: [
      { texto: 'O CBD reduziu significativamente a ansiedade medida pelas duas escalas utilizadas no estudo.' },
      { texto: 'Os participantes tratados com CBD apresentaram melhora em comparação ao grupo controle.' },
      { texto: 'Os autores concluíram que "o CBD pode ser uma opção útil para tratar ansiedade social".' },
      { texto: 'O perfil de segurança foi favorável durante o período do estudo.' },
    ],
    significado: 'Este estudo é relevante por avaliar o CBD especificamente em adolescentes com transtorno de ansiedade social — uma condição que afeta significativamente a qualidade de vida e a socialização dos jovens. Os resultados positivos em duas medidas diferentes de ansiedade fornecem uma indicação inicial de que o CBD pode ter potencial como opção terapêutica complementar nessa população.',
    limites: [
      'A amostra foi pequena: 37 participantes no total.',
      'O estudo foi conduzido em uma população específica (adolescentes japoneses) — os resultados podem não ser diretamente generalizáveis.',
      'A duração foi curta: apenas 4 semanas de tratamento.',
      'Não foram reportadas limitações formais pelos autores no conteúdo disponível.',
      'Estudos maiores, multicêntricos e com populações diversas são necessários para confirmar os achados.',
    ],
  },
];
